blogproject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from .views import CustomUserCreationView, CustomUserLoginView, CustomUserUpdateView, ManageView, MarkAsSpamThreadView, MarkAsSpamCommentView

app_name = 'accounts'

urlpatterns = [
    path('registrar/', CustomUserCreationView, name='register'),
    path('entrar/', CustomUserLoginView.as_view(), name='login'),
    path('sair/', auth_views.LogoutView.as_view(template_name='user/sair/sair.html'), name='logout'),
    path('esqueci-a-senha/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('atualizar/', CustomUserUpdateView.as_view(), name='update'),
    path('gerenciar/', ManageView.as_view(), name='manage'),
    path('gerenciar/thread/<slug>', MarkAsSpamThreadView.as_view(), name='spamThread'),
    path('gerenciar/comentario/<pk>', MarkAsSpamCommentView.as_view(), name='spamComment'),

]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, re_path
from django.conf import settings
from django.conf.urls.static import static

from pages.views import HomePageView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('noticias/', include('topics.urls', namespace='threads')),
    re_path(r'^chaining/', include('smart_selects.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproject/topics/urls.py
from django.conf.urls import include
from django.urls import path
from django.urls.conf import re_path

from .views import ThreadListView, ThreadDetailView, ThreadCreateView, ThreadEditView,ThreadModerateView

app_name = 'threads'

urlpatterns = [
    path('', ThreadListView.as_view(), name="threadList"),
    path('<str:game>/<str:category>/<str:slug>', ThreadDetailView.as_view(), name='threadDetail'),
    path('<str:game>/<str:category>/<str:slug>/editar', ThreadEditView.as_view(), name='threadEdit'),
    path('<str:game>/<str:category>/<str:slug>/moderar', ThreadModerateView.as_view(), name='threadModerate'),
    path('criar', ThreadCreateView.as_view(), name='threadCreate'),
    re_path(r'^chaining/', include('smart_selects.urls')),

]

blogproject/topics/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django_currentuser.middleware import (
    get_current_user, get_current_authenticated_user)
from django_currentuser.db.models import CurrentUserField
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django_extensions.db.fields import AutoSlugField 
from django.urls import reverse
from smart_selects.db_fields import ChainedForeignKey
from ckeditor.fields import RichTextField
from mptt.models import MPTTModel, TreeForeignKey


from django.conf import settings




class Thread(models.Model):
  title = models.CharField(max_length=100)
  author = CurrentUserField()
  category = models.ForeignKey('ThreadCategory', on_delete=models.SET_NULL, null=True)
  game = models.ForeignKey('ThreadGame', on_delete=models.SET_NULL, null=True)
  message = RichTextField()
  image = models.ImageField(upload_to='image/%Y/%m/%d/', blank=True, null=True)

  flagged = models.BooleanField(default=False)
  reason = models.TextField(blank=True, null=True)
  locked = models.BooleanField(blank=True, default=False)
  isStickied = models.BooleanField(default=False)

  views = models.IntegerField(blank=True, default=0)

  createdAt = models.DateTimeField(default=timezone.now)
  updatedAt = models.DateTimeField(auto_now=True)


  slug = AutoSlugField(populate_from=['id', 'title'], null=True, blank=True)


  def __str__(self):
    return self.title

  def save(self,  *args, **kwargs):
    super(Thread, self).save( *args, **kwargs)

  def get_absolute_url(self):
    return reverse('threads:threadDetail', args=[str(self.game),str(self.category),str(self.slug)])

    
  
  class Meta:
    db_table = 'threads'
    managed = True
    verbose_name = 'Thread'
    verbose_name_plural = 'Threads'

class ThreadCategory(models.Model):
  name = models.CharField(max_length=100)
  game = models.ForeignKey('ThreadGame', blank=True, null=True, related_name='category', on_delete=models.SET_NULL)
  image = models.ImageField(default='category-default.jpg',
                              upload_to='topics/category/img/%Y/%m/%d/')
  slug = models.SlugField(blank=True, null=True)
  
  createdAt = models.DateTimeField(default=timezone.now)
  updatedAt = models.DateTimeField(auto_now=True)


  def save(self, *args, **kwargs):
    if not self.slug and self.name :
      self.slug = slugify(self.name)
    super(ThreadCategory, self).save(*args, **kwargs)

  class Meta:
    verbose_name = 'Thread Category'
    verbose_name_plural = 'Thread Categories'

  def __str__(self):
    return self.name

class ThreadGame(models.Model):
  name = models.CharField(max_length=100)
  image = models.ImageField(default='category-default.jpg',
                              upload_to='topics/category/img/%Y/%m/%d/')
  slug = models.SlugField(blank=True, null=True)
  
  createdAt = models.DateTimeField(default=timezone.now)
  updatedAt = models.DateTimeField(auto_now=True)


  def save(self, *args, **kwargs):
    if not self.slug and self.name :
      self.slug = slugify(self.name)
    super(ThreadGame, self).save(*args, **kwargs)

  class Meta:
    verbose_name = 'Thread Game'
    verbose_name_plural = 'Thread Games'

  def __str__(self):
    return self.name


class ThreadComment(models.Model):
    
    author = CurrentUserField()
    comment = models.TextField(null=False, blank=False)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE,
                                related_name='comments')
    
    createdAt = models.DateTimeField(default=timezone.now)
    updatedAt = models.DateTimeField(auto_now=True)
    
    flagged = models.BooleanField(default=False)
    reason = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ('-createdAt',)

    def __str__(self):
        return f"Comentário de {self.author.email} em {self.thread.title}"

blogproject/topics/forms.py
# Core Django imports.
from django.db.models.fields import BooleanField
from django.forms import ModelForm, TextInput, EmailInput, Textarea, FileInput,Select
from django import forms
from django.contrib.auth.models import User
from ckeditor.widgets import CKEditorWidget



# Blog application imports.
from .models import Thread, ThreadCategory, ThreadComment
from accounts.models import CustomUser


class ThreadCreateForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=ThreadCategory.objects.all(),
                                      empty_label="Select Category",
                                      widget=forms.Select(attrs=
                                                          {
                                                              "class": "form-control selectpicker",
                                                              "type": "text",
                                                              "name": "thread-category",
                                                              "id": "threadCategory",
                                                              "data-live-search": "true"
                                                          }
                                      )
                                    )


    class Meta:

        # Article status constants
        MASCULINO = "MASCULINO"
        FEMININO = "FEMININO"
        OUTROS = "OUTROS"

        # CHOICES
        GENDER_CHOICES = (
            (MASCULINO, 'Masculino'),
            (FEMININO, 'Feminino'),
            (OUTROS, 'Outros'),
        )

        model = Thread
        fields = [
            "title",
            "category", 
            "game", 
            "image", 
            "message", 
        ]
        widgets = {
            'title': TextInput(attrs={
                                     'name': "thread-title",
                                     'class': "form-control",
                                     'placeholder': "Enter Thread Title",
                                     'id': "threadTitle"
                                     }),
            'image': FileInput(attrs={
                                        "class": "form-control clearablefileinput",
                                        "type": "file",
                                        "id": "articleImage",
                                        "name": "thread-image"
                                      }

                               ),

            'body': forms.CharField(widget=CKEditorWidget(config_name="default", attrs={
                       "rows": 5, "cols": 20,
                       'id': 'content',
                       'name': "article_content",
                       'class': "form-control",
                       })),

            'tags': TextInput(attrs={
                                     'name': "tags",
                                     'class': "form-control",
                                     'placeholder': "Example: sports, game, politics",
                                     'id': "tags",
                                     'data-role': "tagsinput"
                                     }),

            'status': Select(choices=GENDER_CHOICES,
                             attrs=
                             {
                                 "class": "form-control selectpicker",
                                 "name": "status", "type": "text",
                                 "id": "articleStatus",
                                 "data-live-search": "true",
                                 "title": "Select Status"
                             }
                             ),
        }

class ThreadModerateForm(forms.ModelForm):

    class Meta:

        model = Thread
        fields = [
            "isStickied",
            "locked", 
            "flagged", 
            "reason", 
        ]
        labels  = {
            "isStickied": "Em Destaque?",
            "locked": "Está Fechado?", 
            "flagged": "É Spam?", 
            "reason":"Motivo", 
        }




class ThreadCommentForm(ModelForm):
    class Meta:
        model = ThreadComment
        fields = ['comment', ]
        widgets = {
            'comment': Textarea(attrs={'name': "contact-form-message",
                                       'rows': "2",
                                       'class': "text-area-messge form-control",
                                       'placeholder': "Insira seu comentário",
                                       'aria - required': "true",
                                       'aria - invalid': "false"
                                       }),
        }



class UserUpdateForm(forms.ModelForm):
    """
        Creates form for user to update their account.
    """
    email = forms.EmailField(widget=
                             forms.EmailInput(attrs={
                                                     'name': "email",
                                                     'id': "email",
                                                     'class': "form-control",
                                                    }
                                              ),
                             )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
        widgets = {

            'first_name': forms.TextInput(attrs={
                'name': "first-name",
                'class': "form-control",
                'id': "first-name"
            }),

            'last_name': forms.TextInput(attrs={
                'name': "last-name",
                'class': "form-control",
                'id': "last-name"
            }),

            'username': forms.TextInput(attrs={
                'name': "username",
                'class': "form-control",
                'id': "username"
            }),
        }

blogproject/topics/views.py
# Standard Python Library imports.
from functools import reduce
import operator

# Core Django imports.
from django.contrib import messages
from django.views.generic import (
    DetailView,
    ListView,
)
from django.views.generic.edit import CreateView, UpdateView


# Blog application imports.
from .models import (
                        Thread, 
                        ThreadCategory, 
                        ThreadComment
    )
from .forms import (
                        ThreadCommentForm,
                        ThreadCreateForm,
                        ThreadModerateForm
    )
from django.http import HttpResponseRedirect

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponseForbidden
from django.views.generic.edit import FormMixin






class ThreadListView(ListView):
    context_object_name = "threads"
    paginate_by = 25
    queryset = Thread.objects.filter(flagged=False)
    template_name = "thread/threadlist.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ThreadCategory.objects.all()
        return context


class ThreadDetailView(FormMixin, DetailView):
    model = Thread
    template_name = 'thread/threaddetail.html'
    form_class = ThreadCommentForm
    success_url = "#"

    def get_context_data(self, **kwargs):
        session_key = f"viewed_article {self.object.slug}"
        if not self.request.session.get(session_key, False):
            self.object.views += 1
            self.object.save()
            self.request.session[session_key] = True
        


        kwargs['article'] = self.object
        kwargs['comment_form'] = ThreadCommentForm()
        kwargs['comments'] = ThreadComment.objects.filter(flagged=False).filter(thread__id=self.object.id)
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.thread = get_object_or_404(Thread,
                                            slug=self.kwargs.get('slug'))
        comment.save()
        messages.success(self.request, "Comment Added successfully")
        return HttpResponseRedirect(self.request.path_info)

class ThreadCreateView(CreateView):
    model = Thread
    form_class = ThreadCreateForm
    template_name = 'thread/threadcreate.html'


class ThreadEditView(UpdateView):
    model = Thread
    form_class = ThreadCreateForm
    template_name = 'thread/threadedit.html'

    def get_object(self):
            return Thread.objects.get(slug=self.kwargs['slug'])



class ThreadModerateView(UpdateView):
    model = Thread
    form_class = ThreadModerateForm
    template_name = 'thread/threadedit.html'

    def get_object(self):
            return Thread.objects.get(slug=self.kwargs['slug'])

blogproject/topics/templates/thread/threaddetail.html
{% extends 'base.html' %}

{% block title %}
{{article.title}} - {{article.category }} | Portal Ongame
{% endblock title %}
{% block head %}


	 <style>
.post-item .text h1 a:after, .post-item .text h1 span:after {
    position: absolute;
    content: '';
    left: 0px;
    top: 2px;
    background: #db2e1c;
    width: 3px;
    height: 17px;
}
ul.breadcrumb {
    background-color: transparent;
    margin-top: 20px;
    font-size: 12px;
    color: black;
}
ul.breadcrumb > li > a {
    background-color: transparent;
    margin-top: 20px;
    font-size: 12px;
    color: black;
}
.post-area .post-info{ position: relative; padding: 30px 0; }

.post-area .post-info .left-area{ height: 70px; width: 70px; border-radius: 100px; overflow: hidden; position: absolute;
	top: 50%; margin-top: -35px; border: 1px solid #fff; box-shadow: 0px 0px 5px rgba(0,0,0,.3); }

.post-area .post-info .middle-area{ padding-left: 90px; display: inline-block; }
.article-author-profile-image {
    width: 50px;
   height: 50px;
   max-width: 50px;
   max-height: 50px;
   object-fit: cover;
  }
  img.article-author-profile-image {
    border-radius: 35px;
}
.google-auto-placed {

    display: none;
}
  .card-body > h2 > a, .title-v1 > h3 {
    display: inline-block;
    width: 100%;
    padding-left: 10px;
    position: relative;
    color: black;
    transition: all 0.5s ease 0s;
    font: 400 30px/32px "Oswald";
  }
  .card-body > h2 > a {

	border-left: 10px red solid;
    padding-left: 10px;
  }
  .tag > p > i {
    padding: 0 8px;
  }
  .tag > a > i {
    padding: 0 8px;
  }
  .article-author-profile-image {
    width: 50px;
    height: 50px;
    max-width: 50px;
    max-height: 50px;
    object-fit: cover;
  }
  img.article-author-profile-image {
    border-radius: 35px;
  }
.google-auto-placed {

    display: none;
}

.tag-item > i {
    margin: 0 10px;
}
.tag-item > a > i {
    margin: 0 10px;
}
.tag {
    font-size: 12px;
}
.titulo-artigo {
    font: 400 36px/36px "Oswald";
    border-left: 10px orange solid;
    margin: 30px;
    padding-left: 10px;
}
.artigo-lista {

    padding: 10px 0;
}

.box-user > .box {
  border-bottom: 1px solid #d7d7d7;
  display: inline-block;
  width: 100%;
}

.box-user > .box > .avatar {
  width: 50px;
  height: 50px;
  border: 3px solid #db2e1c;
  border-radius: 50%;
  float: left;
  margin-right: 20px;
}

.box-user > .box > .avatar > img {
  width: 100%;
  border-radius: 50%;
}

.box-user > .box > .text {
  font-family: "TXGR";
}

.box-user > .box > .text > h3 {
  text-transform: capitalize;
  color: #333333;
  font-size: 16px;
}

.box-user > .box > .text > p {
  font-size: 14px;
  color: #666;
}
.box-user .box {
  background: #fafafa;
  border: 1px solid #efefef;
  display: table;
  padding: 15px;
}
.box-user .avatar {
  width: 120px;
  display: table-cell;
  vertical-align: middle;
  background: #fff;
  padding: 5px;
  border: 1px solid #efefef;
}

.box-user .text {
  display: table-cell;
  vertical-align: middle;
  padding-left: 20px;
}

.box-user h3 {
  font: 700 18px/20px "Oswald";
  color: #000;
  margin-bottom: 5px;
}

.box-user h3 span {
  color: #db2e1c;
  vertical-align: bottom;
  margin-left: 5px;
  font-size: 13px;
}

.box-user p {
  font: 400 14px/18px "Lato";
  color: #a3a3a3;
  margin-bottom: 5px;
}

.box-user .social a:first-child {
  padding-left: 0px;
}

.box-user .social i {
  font-size: 18px;
  color: #959595;
}
  .box-user .avatar, .box-user .text {
    display: inline-block;
    width: auto;
    padding: 0px;
  }
  .box-user .text {

    padding: 10px;
  }
  .box-user .avatar {
    margin-bottom: 30px;
  }
  .box {
  display: inline-block;
  width: 100%;
}
.tag-cat {
  margin-top: 30px;
  padding-top: 15px;
  border-top: 1px solid #efefef;
}

.tag-cat span {
  display: inline-block;
  color: #fff;
  background: #000;
  font: 400 14px/20px "Oswald";
  padding: 0 15px;
  letter-spacing: 0px;
  text-transform: uppercase;
  height: 20px;
  margin-right: 15px;
}

.tag-cat a {
  font: 400 15px/20px "Lato";
}
  .artigos-semelhantes > .text > h2 {
    display: inline-block;
    width: 100%;
    padding-left: 10px;
    position: relative;
    color: black;
    transition: all 0.5s ease 0s;
    font: 400 30px/32px "Oswald";
    padding-left: 10px;
  }
    .artigos-semelhantes > .text > .tag > .date  {
    display: inline-block;
    width: 100%;
    padding-left: 10px;
    position: relative;
    color: black;
    transition: all 0.5s ease 0s;

  }

</style>
   {% endblock head %}
    

{% block body %}
{% load static %}
<a href="{% url 'threads:threadList'%}">Voltar</a>
        <div class="container space-20 space-padding-tb-20">
             <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item">{{article.game}}</li>
                <li class="breadcrumb-item">{{article.category}}</li>
                <li class="breadcrumb-item active"><a href="#">{{article.title}}</a></li>
            </ul>
        </div>
			<div class="container">
            <div class="row">
                
                <div class="col-md-8">
				<h1 class='titulo-artigo'><span style="color:orange;margin:0 15px;">{{article.category}}</span>{{article.title}}</h1>
                    <div class="single-post">
                        <div class="blog-post-item cat-1 box">

                            <div class="content">

                                

                                        <div class="col-xs-12" style="margin-bottom: 10px;">
                                            <a class="avatar" href="#">
                                                <img src="{{ article.author.image.url }}" alt="Profile Image" class="article-author-profile-image"></a>
                                                Por <a class="name" href="#">
                                                    <b>{{ article.author.get_full_name }}</b></a>
                                        </div><!-- post-info -->
                                <div class="tag">
											<div class="container-fluid">
												<div class="row">
													<p class="tag-item">
														<i class="far fa-eye"></i>{{ article.views }} vezes
														<span>/</span>
														<i class="far fa-clock"></i>Há {{article.createdAt|timesince }} 
														<span>  /</span>
														<a class="tag-link" href="#comentarios" title="comments"><i class="fa fa-comments"></i>{{ article.comments.count }} comentários </a>
													</p>
												</div>
											</div>
										</div>
                                <div class="tag-compartilhar">
                                    

                                        <a href="mailto:?subject={{ article.title }}&amp;body=Confira esse artigo {{ request.build_absolute_uri }}" target="_blank">
                                            <button type="button" class="btn btn-primary" style="background-color: #b3b3b3; height: 30px; font-size: 10px; border: 0px;"><i class="fas fa-envelope-open-text"></i> | Compartilhar via email</button>
                                        </a>

                                        <a href="https://www.linkedin.com/sharing/share-offsite/?url={{ request.build_absolute_uri }}"  target="_blank">
                                            <button type="button" class="btn btn-primary" style="background-color: #0a66c2; height: 30px; font-size: 10px; border: 0px;"><i class="fab fa-linkedin"></i> | Compartilhar no LinkedIn</button>
                                        </a>

                                        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">
                                            <button type="button" class="btn btn-primary" style="background-color: #0b86ee; height: 30px; font-size: 10px; border: 0px;"><i class="fab fa-facebook-square"></i> | Compartilhar no Facebook</button>
                                        </a>

                                        <a href="http://twitter.com/share?text={{ article.title }}. &url={{ request.build_absolute_uri }}" target="_blank">
                                            <button type="button" class="btn btn-primary" style="background-color: #1da1f2; height: 30px; font-size: 10px; border: 0px;"><i class="fab fa-twitter-square"></i> | Compartilhar no Twitter</button>
                                        </a>

                                        <a href="https://api.whatsapp.com/send?text={{ request.build_absolute_uri }}" target="_blank">
                                            <button type="button" class="btn btn-primary" style="background-color: #06d755; height: 30px; font-size: 10px; border: 0px;"><i class="fab fa-whatsapp-square"></i> | Compartilhar no Whatsapp</button>
                                        </a>

                                        <a href="https://telegram.me/share/url?url={{ request.build_absolute_uri }}&text={{ article.title }}" target="_blank">
                                            <button type="button" class="btn btn-primary" style="background-color: #28a8ea; height: 30px; font-size: 10px; border: 0px;"><i class="fab fa-telegram"></i> | Compartilhar no Telegram</button>
                                        </a>
<hr />
                                {{ article.message | safe }}
                            </div>



                        </div>
                    </div>
                    <!-- End signle-post -->
					<hr>
									<h2 id="comentarios" class='titulo-artigo'>COMENTÁRIOS</h1>
                  {% if user.is_authenticated%}
                  <form method="post">
				{% if form.errors %}
					<div class="alert alert-danger" role="alert">
					Há erros no seu formulário. Revise-os e tente novamente. 
					{{ form.non_field_errors }}
					{% for hidden_field in form.hidden_fields %}
								  {{ hidden_field.errors }}
								  {{ hidden_field }}
								{% endfor %}
					</div>
				{% endif %}
				{% csrf_token %}
				{{comment_form}}
				<button class="w-100 btn btn-lg btn-primary" type="submit">Postar Comentário</button>
				
			</form>
                  
                  {% else %}
                  Você precisa estar logado para comentar nessa publicação. <a href="{% url 'accounts:login'%}?next={{ request.path }}">Entre em sua conta agora mesmo</a> <a href="{% url 'accounts:register'%}">Criar conta</a>
                  {% endif %}
            				{% for comment in comments  %}
                    <div class="box-user space-padding-tb-40">
                        <div class="box">
                            
                                {% if comment.author.image %}
                                <div class="avatar" style="background-image:url('{{ comment.author.image.url }}');background-position: center;background-repeat: no-repeat;background-size: cover;"></div>
                                {% else %}
                                <div class="avatar" style="background-image:url('https://aika.ongame.net/static/img/aika/wallpapers/11.jpg');background-position: center;background-repeat: no-repeat;background-size: cover;"></div>
                                {% endif %}
                            
                            <div class="text">
                                <a href="#"><h3>{{ comment.author.get_full_name }}</h3></a>
                                <p>{{comment.comment}}</p>
                                <div class="social">
                                   
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- End box-user -->
                    {% endfor %}

                </div>
                <div class="col-md-4">

                </div>
            </div>
        </div>




{% endblock body %}
    

blogproject/topics/templates/thread/threadlist.html
{% extends 'base.html' %}

 {% block title %} Anuncios {% endblock title %} 
{% block buttonup %} {% endblock buttonup %} {% block head %} 

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Oswald&display=swap" rel="stylesheet"> 
<style>
  h2 {
    display: inline-block;
    width: 100%;
    padding-left: 10px;
    position: relative;
    color: black;
    transition: all 0.5s ease 0s;
    font: 400 20px/20px "Open Sans",sans-serif;
	border-left: 10px orange solid;
    padding-left: 10px;
  }
  .tag > p > i {
    padding: 0 8px;
  }
  .tag > a > i {
    padding: 0 8px;
  }
  .article-author-profile-image {
    width: 20px;
    height: 20px;
    max-width: 20px;
    max-height: 20px;
    object-fit: cover;
  }
  img.article-author-profile-image {
    border-radius: 35px;
  }
.google-auto-placed {

    display: none;
}

.tag-item > i {
    margin: 0 10px;
}
.tag-item > a > i {
    margin: 0 10px;
}
.tag-item {
    margin: 10px;
}
.tag {
    font-size: 12px;
}
.title-v1 > h3 {
    font: 400 36px/36px "Open Sans",sans-serif;
    border-left: 10px orange solid;
    margin: 30px;
    padding-left: 10px;
}
.artigo-lista {

    padding: 10px 0;
}
.artigo-publicidade {
    max-width: 900px;
}
a article {
    color:#000;
    text-decoration: none;
}
.tag-edit {
    margin-right: 22px;
    flex: auto;
}
</style>
{% endblock head%}{% block body %} {% load static %} {% load l10n %}
<div class="container=fluid">
    <div class="container-fluid">
        <div class="row row-eq-height" style="background:#f8f9fa;">
            <div class="col-xs-12 col-md-8">
                {% for thread in threads  %}
                    <a class="images" href="{{ thread.get_absolute_url }}" title="{{ thread.title }}">
                        <article style="background:#fff;border: 1px solid rgba(150, 150, 150, .2); margin:10px;border-radius:5px;">
                            <div style="margin: 5px;">
                                <img src="{{ thread.author.image.url }}" alt="Profile Image"  class="article-author-profile-image"/>
                                Por <b>{{ thread.author.get_full_name }}</b>
                            </div> 
                            <h2>{{ thread.title }}</h2>
                            {% if thread.image %}
                                <img src="{{ thread.image.url }}" class="img-responsive">
                            {% endif %}

                            <div class="container-fluid">
                                <div class="row">
                                    <p class="tag-item">
                                        <i class="far fa-eye"></i>{{ thread.views }} vezes 
                                        <span>/</span>
                                        <i class="fa fa-comments"></i>{{ thread.comments.count }} comentários
                                    </p>
                                    <p class="tag-edit" >
                                        {% if request.user == thread.author or request.user.is_staff %}
                                            <a href="{% url 'threads:threadEdit' thread.game thread.category thread.slug%}"><button class="btn btn-outline-success" style="float:right;">Editar Postagem</button></a>
                                        {%endif%}
                                        {% if request.user.is_staff %}
                                            <a href="{% url 'threads:threadModerate' thread.game thread.category thread.slug%}"><button class="btn btn-outline-success" style="float:right;">Moderar Postagem</button></a>
                                        {%endif%}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </a>
                {% endfor %}
            </div>


		</div>

    </div>
</div>






  {% endblock body %}