blogproject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from .views import CustomUserCreationView, CustomUserLoginView, CustomUserUpdateView, ManageView, MarkAsSpamThreadView, MarkAsSpamCommentView

app_name = 'accounts'

urlpatterns = [
    path('registrar/', CustomUserCreationView, name='register'),
    path('entrar/', CustomUserLoginView.as_view(), name='login'),
    path('sair/', auth_views.LogoutView.as_view(template_name='user/sair/sair.html'), name='logout'),
    path('esqueci-a-senha/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('atualizar/', CustomUserUpdateView.as_view(), name='update'),
    path('gerenciar/', ManageView.as_view(), name='manage'),
    path('gerenciar/thread/<slug>', MarkAsSpamThreadView.as_view(), name='spamThread'),
    path('gerenciar/comentario/<pk>', MarkAsSpamCommentView.as_view(), name='spamComment'),

]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, re_path
from django.conf import settings
from django.conf.urls.static import static

from pages.views import HomePageView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('noticias/', include('topics.urls', namespace='threads')),
    re_path(r'^chaining/', include('smart_selects.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproject/topics/urls.py
from django.conf.urls import include
from django.urls import path
from django.urls.conf import re_path

from .views import ThreadListView, ThreadDetailView, ThreadCreateView, ThreadEditView,ThreadModerateView

app_name = 'threads'

urlpatterns = [
    path('', ThreadListView.as_view(), name="threadList"),
    path('<str:game>/<str:category>/<str:slug>', ThreadDetailView.as_view(), name='threadDetail'),
    path('<str:game>/<str:category>/<str:slug>/editar', ThreadEditView.as_view(), name='threadEdit'),
    path('<str:game>/<str:category>/<str:slug>/moderar', ThreadModerateView.as_view(), name='threadModerate'),
    path('criar', ThreadCreateView.as_view(), name='threadCreate'),
    re_path(r'^chaining/', include('smart_selects.urls')),

]

blogproject/accounts/models.py
# Django Imports
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _

# My Project Imports
from .managers import CustomUserManager


# Article status constants
MASCULINO = "MASCULINO"
FEMININO = "FEMININO"
OUTROS = "OUTROS"
# CHOICES
GENDER_CHOICES = (
(MASCULINO, 'Masculino'),
(FEMININO, 'Feminino'),
(OUTROS, 'Outros'),
)


# Model for Custom User using AbstractBaseUser
class CustomUser(AbstractBaseUser, PermissionsMixin):
    # Access Info
    email = models.EmailField(_('email address'), unique=True)
    
    # User Info
    firstName = models.CharField(_('name'), max_length=100,blank=True, null=True)
    lastName = models.CharField(_('last name'), max_length=100,blank=True, null=True)
    gender = models.CharField(_('gender'), choices=GENDER_CHOICES,default='MASCULINO', max_length=100,blank=True, null=True)
    birthDate = models.DateField(_('birth date'), blank=True, null=True)
    image = models.ImageField(default='profile-pic-default.jpg',
                              upload_to='picprofile'
    )
    
    # Automatic filled Items
    joinedAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    # AbstractBaseUser Paramenters
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    def get_full_name(self):
        if self.firstName or self.lastName:
            return ("%s %s" % (self.firstName, self.lastName)).strip()
        return self.email

    class Meta:
        db_table = 'userData'
        managed = True
        verbose_name = 'User'
        verbose_name_plural = 'Users'
    

blogproject/accounts/forms.py
from django import forms
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import CustomUser
from topics.models import ThreadComment


class CustomUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    checkBox = forms.BooleanField(required = True, label='Li e estou de acordo com os Termos de Uso da Ongame Entretenimento®..',)


    class Meta:
        model = CustomUser
        fields = (
        'email',

    )

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class CustomUserChangeForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class UserUpdateForm(forms.ModelForm):
    """
        Creates form for user to update their account.
    """


    class Meta:
        model = CustomUser
        fields = ['firstName', 'lastName', 'gender', 'birthDate', 'image']
        widgets = {

            'firstName': forms.TextInput(attrs={
                'name': "first-name",
                'class': "form-control",
                'id': "first-name"
            }),

            'lastName': forms.TextInput(attrs={
                'name': "last-name",
                'class': "form-control",
                'id': "last-name"
            }),
        }


class FlagAsSpamForm(forms.ModelForm):

    class Meta:
        model = ThreadComment
        fields = (
        'flagged',
        'reason'

    )

blogproject/accounts/views.py
from django.contrib.auth.views import LoginView
from django.urls.base import reverse_lazy
from django.views import generic
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView




from .models import CustomUser
from topics.models import ThreadComment, Thread

from .forms import CustomUserCreationForm, FlagAsSpamForm, UserUpdateForm

def CustomUserCreationView(request):
    context = {}
    if request.POST:
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('home')
        else:
            context['registration_form'] = form
    else:
        form = CustomUserCreationForm()
        context['registration_form'] = form
    return render(request, 'user/registro/criarUser.html', context)


class CustomUserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'user/entrar/entrar.html'
    success_url = '/'
    success_message = "You were successfully logged in"




class CustomUserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = CustomUser
    form_class = UserUpdateForm
    success_url = reverse_lazy('home')
    template_name = 'user/update/update.html'

    def get_object(self):
            return self.request.user

    
class ManageView(ListView):
    context_object_name = "comments"
    queryset = ThreadComment.objects.all()
    template_name = "user/adm/manage.html"

    def get_context_data(self, **kwargs):
        kwargs['threads'] = Thread.objects.all
        context = super().get_context_data(**kwargs)
        return context



class MarkAsSpamThreadView(LoginRequiredMixin, generic.UpdateView):
    model = Thread
    template_name = 'user/adm/markasspam.html'
    fields = ['flagged']
    success_url = "/noticias"
    pk_field = 'id'
    pk_url_kwarg = 'id'

    def get_object(self):
         return Thread.objects.get(slug=self.kwargs['slug'])

class MarkAsSpamCommentView(LoginRequiredMixin, generic.UpdateView):
    model = ThreadComment
    template_name = 'user/adm/markasspam.html'
    fields = ['flagged']
    success_url = "/noticias"
    pk_field = 'id'
    pk_url_kwarg = 'id'

    def get_object(self):
         return Thread.objects.get(id=self.kwargs['id'])

blogproject/accounts/templates/user/adm/manage.html
{% extends 'base.html' %}

 {% block title %} Anuncios {% endblock title %} 
{% block buttonup %} {% endblock buttonup %} {% block head %} 

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Oswald&display=swap" rel="stylesheet"> 
<style>
  .card-body > h2 > a {
    display: inline-block;
    width: 100%;
    padding-left: 10px;
    position: relative;
    color: black;
    transition: all 0.5s ease 0s;
    font: 400 30px/32px "Oswald";
	border-left: 10px orange solid;
    padding-left: 10px;
  }
  .tag > p > i {
    padding: 0 8px;
  }
  .tag > a > i {
    padding: 0 8px;
  }
  .article-author-profile-image {
    width: 50px;
    height: 50px;
    max-width: 50px;
    max-height: 50px;
    object-fit: cover;
  }
  img.article-author-profile-image {
    border-radius: 35px;
  }
.google-auto-placed {

    display: none;
}

.tag-item > i {
    margin: 0 10px;
}
.tag-item > a > i {
    margin: 0 10px;
}
.tag {
    font-size: 12px;
}
.title-v1 > h3 {
    font: 400 36px/36px "Oswald";
    border-left: 10px orange solid;
    margin: 30px;
    padding-left: 10px;
}
.artigo-lista {

    padding: 10px 0;
}
.artigo-publicidade {
    max-width: 900px;
}
</style>


{% endblock head%}{% block body %} {% load static %} {% load l10n %}
{% if request.user.is_staff %}
<div class="container=fluid">

      <div class="container-fluid">
        <div class="technnology box space-30 row row-eq-height">
          <div class="col-xs-12 col-md-12">
            <div class="title-v1">
              <h3>Ultimos Ativos</h3>
            </div>

            <!-- End title -->
			<div class='container-fluid'>
				<div class='row'>
					<div class="col-xs-12 col-md-12">
						<div class='container-fluid'>
                        <hr>
            				{% for thread in threads  %}
							<div class='row row-eq-height artigo-lista'>
								<div class="d-flex flex-grow-1">
									<div class="card-body">
										<h2><a href="{% url 'accounts:spamThread' thread.slug%}" title="title" >{{ thread.title }}</a></h2>
										<div>{{ thread.message|safe }}</div>
										<div style="margin-bottom: 10px">
											<a class="avatar" href="#">
												<img src="{{ thread.author.image.url }}" alt="Profile Image"  class="article-author-profile-image"/>
											</a>
											Por <a class="name" href="#" > <b>{{ thread.author.get_full_name }}</b></a>
										</div>
										<!-- post-info -->

										<div class="d-flex justify-content-between align-items-center">
											<div class="btn-group">
												<a href="{% url 'accounts:spamThread' thread.slug%}" title="SeeMore" class="btn btn-sm btn-outline-secondary read-more" style="width: 100%">Ver mais</a>
											</div>
										</div>
									</div>
								</div>

							</div>
                            <hr>
							{% endfor %}
            				{% for comment in comments  %}
							<div class='row row-eq-height artigo-lista'>
								<div class="d-flex flex-grow-1">
									<div class="card-body">
										<h2><a href="{{ comment.get_absolute_url }}" title="title" >{{ comment.comment }}</a></h2>
																				<div>{{ comment.comment|safe }}</div>

										<div style="margin-bottom: 10px">
											<a class="avatar" href="#">
												<img src="{{ comment.author.image.url }}" alt="Profile Image"  class="article-author-profile-image"/>
											</a>
											Por <a class="name" href="#" > <b>{{ comment.author.get_full_name }}</b></a>
										</div>
										<!-- post-info -->

										<div class="d-flex justify-content-between align-items-center">
											<div class="btn-group">
												<a href="{% url 'accounts:spamComment' comment.id%}" title="SeeMore" class="btn btn-sm btn-outline-secondary read-more" style="width: 100%">Ver mais</a>
											</div>
										</div>
									</div>
								</div>

							</div>
                            <hr>
							{% endfor %}
						</div>
					</div>
          <nav aria-label="" class="add_top_20">
					<ul class="pagination pagination-sm">
						{% if page_obj.has_previous %}
						<li class="page-item active">
							<a class="page-link" href="?page=1" >Primeira</a>
						</li>
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Anterior</a>
						</li>
						{% endif %}
						{% for pages in page_obj.paginator.page_range %}
						{% if page_obj.number == pages %}
						<li class="page-item active"><a href="" class="page-link">{{pages}}</a></li>
						{% else %}
						<li class="page-item"><a href="?page={{ pages }}" class="page-link">{{pages}}</a></li>
						{% endif %}

								{% endfor %}

								{% if page_obj.has_next %}
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.next_page_number }}">Próximo</a>
						</li>
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Último</a>
						</li>
						{% endif %}
					</ul>
				</nav>
				<!-- /pagination -->
				</div>
					<!-- End item -->
			</div>

          </div>
        </div>
      </div>


  {% else %}
{% include 'utils/isstaff.html' %}


{% endif %}


  {% endblock body %}

blogproject/accounts/templates/user/adm/markasspam.html
{% block body %}
{% if request.user.is_staff %}
{% load static %}
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Moderação de Comentários</title>

    

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
	  #id_username, #id_password1, #id_password2, #id_email, #id_bio, #id_gender, #id_birthDate{
		  	display: block;
			width: 100%;
			padding: .375rem .75rem;
			font-size: 1rem;
			font-weight: 400;
			line-height: 1.5;
			color: #212529;
			background-color: #fff;
			background-clip: padding-box;
			border: 1px solid #ced4da;
			-webkit-appearance: none;
			-moz-appearance: none;
			appearance: none;
			border-radius: .25rem;
				border-bottom-right-radius: 0.25rem;
				border-bottom-left-radius: 0.25rem;
			transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	  }
	  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
}
body {
    background-color: #222;
    background-image: url(https://imagem.ongame.net/background/ongame_2021.jpg);
    background-position: top center;
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-size: cover;
    color:#fff;
}
.form-signin {
    padding: 20px;
    border-radius: 6px;
    background-color: #0D0D0D;
    color:#fff;
}
label:last-of-type {
    float: right;
    font-size: 13px;
    width: 80%;
    margin:10px;
}
input#id_checkBox {
    margin: 20px 0;
}
    </style>

    
    <!-- Custom styles for this template -->
  </head>
	<body class="text-center">
			<div style="margin-top:50px;">
			</div>
				<img class="mb-4" src="https://minhaconta.ongame.net/static/svg/logo-branco.svg" style="width:200px;" alt="" >
				<h1 class="h3 mb-3 fw-normal">Tenha acesso gratuito a todos os jogos da Ongame!</h1>
  		{% if user.is_authenticated %}
		  <main class="form-signin">
			<form method="post" action="">
				{% if form.errors %}
					<div class="alert alert-danger" role="alert">
					Há erros no seu formulário. Revise-os e tente novamente.
					{{ form.non_field_errors }}
					{% for hidden_field in form.hidden_fields %}
								  {{ hidden_field.errors }}
								  {{ hidden_field }}
								{% endfor %}
					</div>
				{% endif %}
				{% csrf_token %}
				{{form.as_p}}
				<button class="w-100 btn btn-lg btn-primary" type="submit">Atualizar dados</button>
				
			</form>
			</main>
			<h6 class="text-center link_bright"> Já tem uma conta? <strong><a href="#">Entre agora</a></strong>. </h6>
			<h6 class="text-center link_bright"><a href="#">Voltar para a página principal</a>. </h6>
		{% else %}
			<p>Olá {{ user.username }}, parece que você já está logado em nosso sistema e por questões de segurança, desabilitamos essa página.</p>
			
			{% endif %}
    
	<p class="mt-5 mb-3 text-muted">Ongame Entretenimento © 2021 Todos os direitos reservados.</p>


    
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body></html>


  {% else %}
{% include 'utils/isstaff.html' %}


{% endif %}
{% endblock body %}